version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
    - .:/otp/app
    - /opt/app/node_modules
  db:
    image: mongo
    container_name: mongo_server
    environment:
      MONGO_INITDB_DATABASE: bank
    expose:
      - "27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongodata:
